server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

# ==== Security ====
jwt.secret=${JWT_SECRET}

# GATEWAY
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only

# PATH / ROLE
auth.gateway.security.ignored-paths=/user-service/api/auth,/user-service/api/internal/auth,/attendance-service/api/devices,/attendance-service/api/internal/admin/fingerprints/enroll/sse,/attendance-service/ws,/chat-service/api/internal,/v3/api-docs,/swagger-ui,/webjars,/user-service/v3/api-docs,/academic-service/v3/api-docs,/attendance-service/v3/api-docs,/score-service/v3/api-docs,/chat-service/v3/api-docs,/admin-service/v3/api-docs

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-origins=${ALLOWED_ORIGINS}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].exposed-headers=Authorization
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allow-credentials=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].max-age=3600
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_FIRST

# Documentation
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Academic Service
springdoc.swagger-ui.urls[1].url=/academic-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Attendance Service
springdoc.swagger-ui.urls[2].url=/attendance-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Score Service
springdoc.swagger-ui.urls[3].url=/score-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Admin Service
springdoc.swagger-ui.urls[4].url=/admin-service/v3/api-docs
springdoc.swagger-ui.urls[5].name=Chat Service
springdoc.swagger-ui.urls[5].url=/chat-service/v3/api-docs
