server.port=8080
spring.application.name=api-gateway

# EUREKA
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT / SECRET
jwt.secret=${JWT_SECRET}S

# GATEWAY
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only

# PATH / ROLE
auth.gateway.security.ignored-paths[0]=/user-service/api/auth,/user-service/api/internal/auth

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-headers=Authorization,Content-Type
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].exposed-headers=Authorization
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allow-credentials=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].max-age=3600
