services:
  # ===== Discovery Service =====
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - micro-net

  # ===== PgAdmin =====
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - micro-net
    depends_on:
      - postgres-user
      - postgres-academic
      - postgres-score
      - postgres-attendance

  # ===== API Gateway =====
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - micro-net

  # ===== PostgreSQL Databases =====
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./user-service/init:/docker-entrypoint-initdb.d
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - micro-net

  postgres-academic:
    image: postgres:15
    container_name: postgres-academic
    environment:
      POSTGRES_DB: ${ACADEMIC_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./academic-service/init:/docker-entrypoint-initdb.d
      - postgres_academic_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - micro-net

  postgres-score:
    image: postgres:15
    container_name: postgres-score
    environment:
      POSTGRES_DB: ${SCORE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./score-service/init:/docker-entrypoint-initdb.d
      - postgres_score_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - micro-net

  postgres-attendance:
    image: postgres:15
    container_name: postgres-attendance
    environment:
      POSTGRES_DB: ${ATTENDANCE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./attendance-service/init:/docker-entrypoint-initdb.d
      - postgres_attendance_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - micro-net

  # ===== Microservices =====
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      DB_URL: ${USER_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      discovery-service: { condition: service_healthy }
      postgres-user: { condition: service_started }
    ports:
      - "8081:8080"
    networks:
      - micro-net

  academic-service:
    build: ./academic-service
    container_name: academic-service
    environment:
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      DB_URL: ${ACADEMIC_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASS: ${MAIL_PASSWORD}
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
    depends_on:
      discovery-service: { condition: service_healthy }
      postgres-academic: { condition: service_started }
      redis: { condition: service_healthy }
    ports:
      - "8082:8080"
    networks:
      - micro-net

  score-service:
    build: ./score-service
    container_name: score-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      DB_URL: ${SCORE_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    depends_on:
      discovery-service: { condition: service_healthy }
      postgres-score: { condition: service_started }
    ports:
      - "8083:8080"
    networks:
      - micro-net

  attendance-service:
    build: ./attendance-service
    container_name: attendance-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      DB_URL: ${ATTENDANCE_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASS: ${MAIL_PASSWORD}
      ADMIN_SERVICE_URL: ${ADMIN_SERVICE_URL}
      # MQTT mTLS Configuration
      MQTT_BROKER_URL: ${MQTT_BROKER_URL}
      MQTT_TLS_ENABLED: "true"
      MQTT_TRUSTSTORE_PATH: ${MQTT_TRUSTSTORE_PATH}
      MQTT_TRUSTSTORE_PASSWORD: ${MQTT_TRUSTSTORE_PASSWORD}
      MQTT_KEYSTORE_PATH: ${MQTT_KEYSTORE_PATH}
      MQTT_KEYSTORE_PASSWORD: ${MQTT_KEYSTORE_PASSWORD}
      MQTT_KEYSTORE_TYPE: ${MQTT_KEYSTORE_TYPE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      # Mount folder client certs cho Backend đọc file .p12 và .jks
      - ./mosquitto/certs/client:/app/certs:ro
    depends_on:
      discovery-service: { condition: service_healthy }
      postgres-attendance: { condition: service_started }
      mosquitto: { condition: service_started }
    ports:
      - "8084:8080"
    networks:
      - micro-net

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    user: "1883:1883"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/config/password.txt:/mosquitto/config/password.txt:ro
      - ./mosquitto/certs:/mosquitto/certs:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - micro-net
    healthcheck:
      # Kiểm tra cổng 8883 thay vì dùng lệnh sub vì vướng mTLS
      test: [ "CMD-SHELL", "netstat -an | grep 8883 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    
  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - micro-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat-service:
    build: ./chat-service
    container_name: chat-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      FIREBASE_SERVICE_ACCOUNT_BASE64: ${FIREBASE_SERVICE_ACCOUNT_BASE64}
    depends_on:
      discovery-service: { condition: service_healthy }
    ports:
      - "8086:8080"
    networks:
      - micro-net

  admin-service:
    build: ./admin-service
    container_name: admin-service
    environment:
      TZ: Asia/Ho_Chi_Minh
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_SERVER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    depends_on:
      discovery-service: { condition: service_healthy }
    ports:
      - "8085:8080"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  pgadmin_data:
  postgres_user_data:
  postgres_academic_data:
  postgres_score_data:
  postgres_attendance_data:
  mosquitto_data:
  mosquitto_log:
