# --- Lưu trữ dữ liệu ---
persistence true
persistence_location /mosquitto/data/

# --- Nhật ký (Logs) - SỬA Ở ĐÂY ĐỂ XEM ĐƯỢC DOCKER LOGS ---
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_type debug
connection_messages true

# --- Cấu hình bảo mật mặc định (QUAN TRỌNG) ---
allow_anonymous false

# --- Listener mTLS (Cổng 8883) ---
listener 8883 0.0.0.0
# Đảm bảo đường dẫn này khớp chính xác với cấu trúc trong container
cafile /mosquitto/certs/ca/ca.crt
certfile /mosquitto/certs/server/mosquitto.crt
keyfile /mosquitto/certs/server/mosquitto.key

# Kích hoạt mTLS
require_certificate true

# Sử dụng Common Name (CN) làm Username
use_identity_as_username true

# Giao thức
tls_version tlsv1.2
