spring.application.name=admin-service
logging.level.com.lqm=DEBUG
server.port=8080
debug=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

# ==== Security ====
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}

# ==== Web ====
spring.mvc.hiddenmethod.filter.enabled=true

# ==== Profiles & Logging ====
spring.profiles.active=prod
spring.cloud.openfeign.circuitbreaker.enabled=false

# ==== WebSocket (attendance-service) ====
attendance.ws.url=${ATTENDANCE_WS_URL}

# ==== Multipart Upload ====
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
