spring.application.name=admin-service
logging.level.com.lqm=DEBUG
server.port=8080
debug=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

# ==== Security ====
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}

# ==== Web ====
spring.mvc.hiddenmethod.filter.enabled=true

# ==== Profiles & Logging ====
spring.profiles.active=prod
# ==========================================
# Resilience4j Circuit Breaker Configuration
# ==========================================
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

# ==== WebSocket (attendance-service) ====
attendance.ws.url=${ATTENDANCE_WS_URL:http://localhost:8084/ws}
