spring.application.name=chat-service
server.port=8080

# Eureka Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

# Firebase Admin SDK - Service Account JSON (Base64 encoded or file path)
firebase.service-account.base64=${FIREBASE_SERVICE_ACCOUNT_BASE64}

# ==== RabbitMQ ====
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
